# Generated by Django 4.2.6 on 2023-12-06 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_task_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='price',
            field=models.FloatField(null=True),
        ),
    ]
